# install docker on a specific host. will be prompted
- name: Install Docker on Ubuntu
  hosts: "{{target}}"
  vars_prompt:
    - name: target
      prompt: "Provide host(s) or group(s) to run against"
      private: no
      default: all
    - name: ansible_user
      prompt: "User"
      private: no
    - name: ansible_password
      prompt: "User SSH Password"
      private: yes
    - name: ansible_become_pass
      prompt: "User sudo/become Password"
      #default: "{{ ansible_password }}"
      private: yes
  vars:
    arch_mapping: # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64

  tasks:
    - name: Remove old docker packages if present
      become: true
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose
          - docker-compose-v2
          - docker-doc
          - podman-docker
        state: absent

    - name: Update and upgrade all packages to the latest version
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600

    - name: Install required packages
      become: true
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common

    - name: Create directory for Docker's GPG key
      become: true
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker's official GPG key
      become: true
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Print architecture variables
      ansible.builtin.debug:
        msg: "Architecture: {{ ansible_architecture }}, Codename: {{ ansible_lsb.codename }}"

    - name: Add Docker repository
      become: true
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        filename: docker
        state: present

    - name: Install Docker and related packages
      become: true
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: install python dependencies
      become: true
      ansible.builtin.apt:
        update_cache: yes
        state: latest
        name:
          - python3-pip
          - python3-docker

    - name: install/ update python modules needed for ansible docker
      ansible.builtin.pip:
        name:
          - docker
          - requests
        state: latest
