# update a specific ubuntu host. will be prompted
- name: update ubuntu servers
  hosts: "{{target}}"
  vars_prompt:
    - name: target
      prompt: "Provide host(s) or group(s) to run against"
      private: no
      default: all
    - name: ansible_user
      prompt: "User"
      private: no
    - name: ansible_password
      prompt: "User SSH Password"
      private: yes
    - name: ansible_become_pass
      prompt: "User sudo/become Password"
      private: yes

  tasks:
    - name: update servers
      become: true
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: reboot if required
      become: true
      reboot:
      when: reboot_required_file.stat.exists == true
